"""empty message

Revision ID: e53e3c4cc02c
Revises: None
Create Date: 2017-02-09 22:44:05.881097

"""

# revision identifiers, used by Alembic.
revision = 'e53e3c4cc02c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('abbr', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lexicals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Unicode(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translations',
    sa.Column('source_lexical_id', sa.Integer(), nullable=False),
    sa.Column('dest_lexical_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dest_lexical_id'], ['lexicals.id'], ),
    sa.ForeignKeyConstraint(['source_lexical_id'], ['lexicals.id'], ),
    sa.PrimaryKeyConstraint('source_lexical_id', 'dest_lexical_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translations')
    op.drop_table('lexicals')
    op.drop_table('languages')
    # ### end Alembic commands ###
